--- 
- name : install apache server on ubuntu
  hosts: all 
  become: yes
  tasks:
   - name: install apache2
     ansible.builtin.apt:
       name: apache2 
       state: present 
       update_cache: yes